#!/bin/bash

echo "🔍 Azure Database Connection Diagnostic Commands"
echo "==============================================="
echo ""
echo "You can run these commands in Azure Console (Kudu/SSH) to test connections:"
echo ""

echo "1. 🌐 Access Azure Console:"
echo "   - Go to: https://techbuy-webapp-agbgf2gbgud8apaw.scm.centralindia-01.azurewebsites.net/"
echo "   - Or: Azure Portal → App Service → Development Tools → Console"
echo "   - Or: Azure Portal → App Service → SSH"
echo ""

echo "2. 📁 Navigate to your app directory:"
echo "   cd /home/site/wwwroot"
echo ""

echo "3. 🔧 Check Environment Variables:"
echo "   echo \$DB_HOST"
echo "   echo \$DB_DATABASE"
echo "   echo \$DB_USERNAME"
echo "   echo \$MONGODB_HOST"
echo "   echo \$MONGODB_DATABASE"
echo ""

echo "4. 🗄️ Test PostgreSQL Connection:"
echo "   php artisan tinker --execute=\""
echo "   try {"
echo "       \\\$pdo = new PDO("
echo "           'pgsql:host=' . env('DB_HOST') . ';dbname=' . env('DB_DATABASE'),"
echo "           env('DB_USERNAME'),"
echo "           env('DB_PASSWORD')"
echo "       );"
echo "       echo 'PostgreSQL: Connected successfully!' . PHP_EOL;"
echo "       \\\$result = \\\$pdo->query('SELECT version()');"
echo "       echo 'PostgreSQL Version: ' . \\\$result->fetchColumn() . PHP_EOL;"
echo "   } catch (Exception \\\$e) {"
echo "       echo 'PostgreSQL Error: ' . \\\$e->getMessage() . PHP_EOL;"
echo "   }"
echo "   \""
echo ""

echo "5. 🍃 Test MongoDB Connection:"
echo "   php artisan tinker --execute=\""
echo "   try {"
echo "       \\\$manager = new MongoDB\\\Driver\\\Manager("
echo "           'mongodb://' . env('MONGODB_HOST') . ':' . env('MONGODB_PORT')"
echo "       );"
echo "       \\\$command = new MongoDB\\\Driver\\\Command(['ping' => 1]);"
echo "       \\\$result = \\\$manager->executeCommand(env('MONGODB_DATABASE'), \\\$command);"
echo "       echo 'MongoDB: Connected successfully!' . PHP_EOL;"
echo "   } catch (Exception \\\$e) {"
echo "       echo 'MongoDB Error: ' . \\\$e->getMessage() . PHP_EOL;"
echo "   }"
echo "   \""
echo ""

echo "6. 🧪 Test Laravel Database:"
echo "   php artisan tinker --execute=\""
echo "   try {"
echo "       \\\$users = \\\App\\\Models\\\User::count();"
echo "       echo 'Users count: ' . \\\$users . PHP_EOL;"
echo "       \\\$products = \\\App\\\Models\\\Product::count();"
echo "       echo 'Products count: ' . \\\$products . PHP_EOL;"
echo "   } catch (Exception \\\$e) {"
echo "       echo 'Laravel DB Error: ' . \\\$e->getMessage() . PHP_EOL;"
echo "   }"
echo "   \""
echo ""

echo "7. 🔄 Run Migrations and Seeding:"
echo "   php artisan migrate:status"
echo "   php artisan migrate:fresh --force"
echo "   php artisan db:seed --force"
echo ""

echo "8. 📊 Check Application Logs:"
echo "   tail -f /home/LogFiles/application_logs.txt"
echo "   # or"
echo "   cat /home/LogFiles/application_logs.txt | grep -i error"
echo ""

echo "9. 🔍 Check Web Server Logs:"
echo "   tail -f /home/LogFiles/http_logs.txt"
echo ""

echo "10. ⚙️ Clear Laravel Cache:"
echo "    php artisan config:clear"
echo "    php artisan cache:clear"
echo "    php artisan route:clear"
echo "    php artisan view:clear"
echo ""

echo "💡 Quick Diagnostic One-Liner:"
echo "php artisan tinker --execute=\"echo 'DB_HOST: ' . env('DB_HOST') . PHP_EOL; echo 'DB_DATABASE: ' . env('DB_DATABASE') . PHP_EOL; try { \\\$count = \\\App\\\Models\\\User::count(); echo 'Connected! Users: ' . \\\$count . PHP_EOL; } catch (Exception \\\$e) { echo 'Error: ' . \\\$e->getMessage() . PHP_EOL; }\""
