#!/bin/bash

echo "Azure Laravel Deployment Status Checker"
echo "======================================="
echo ""
echo "Deployment pushed to GitHub. Monitoring Azure deployment..."
echo ""
echo "🔗 GitHub Repository: https://github.com/SyntaxIDK/TechBuy-laravel"
echo "🔗 Azure Portal: https://portal.azure.com/#@kaveeshasenarathneoutlook.onmicrosoft.com/resource/subscriptions/ca61cf33-9700-4d8c-9ffc-34c2a0cc66ad/resourceGroups/techbuy-rg/providers/Microsoft.Web/sites/techbuy-webapp"
echo ""
echo "Wait 2-3 minutes for deployment to complete, then test:"
echo ""
echo "1. 🏠 Homepage: https://techbuy-webapp-agbgf2gbgud8apaw.centralindia-01.azurewebsites.net/"
echo "2. 🧪 Laravel Test: https://techbuy-webapp-agbgf2gbgud8apaw.centralindia-01.azurewebsites.net/azure-test.php"
echo ""
echo "Expected results after this fix:"
echo "✅ Homepage should load without 404 error"
echo "✅ Laravel should have proper .env configuration"
echo "✅ Database connection should work"
echo "✅ Proper styling with HTTPS assets"
echo ""
echo "If still having issues, check Azure App Service logs or run additional diagnostics."
echo ""
echo "Next steps if needed:"
echo "1. Configure Azure Application Settings (see AZURE_ENVIRONMENT_SETUP.md)"
echo "2. Add MongoDB configuration if needed"
echo "3. Set up user registration/login"
