#!/bin/bash

echo "🚀 DEPLOYING AZURE FILE UPLOAD FIX"
echo "=================================="

echo "🔧 This deployment will:"
echo "1. ✅ Configure persistent file storage using /home/LogFiles"
echo "2. ✅ Update nginx to serve uploaded files correctly"
echo "3. ✅ Fix filesystem configuration for Azure"
echo "4. ✅ Create test script for upload verification"
echo "5. ✅ Set up proper storage directories and permissions"
echo ""

# Commit and push the file upload fixes
git add .
git commit -m "Fix Azure file uploads: persistent storage + nginx configuration"
git push origin main

echo ""
echo "🚀 DEPLOYMENT PUSHED TO AZURE!"
echo ""
echo "📋 WHAT HAPPENS NEXT:"
echo "1. 🔄 Azure will automatically deploy in 2-3 minutes"
echo "2. 📁 Persistent storage will be configured in /home/LogFiles/storage"
echo "3. 🌐 nginx will serve uploaded files from persistent location"
echo "4. 🔗 Storage symlink will be created for proper file access"
echo ""
echo "🔍 AFTER DEPLOYMENT:"
echo ""
echo "📝 STEP 1: SSH into Azure and run startup script:"
echo "   cd /home/site/wwwroot"
echo "   bash startup.sh"
echo ""
echo "📝 STEP 2: Test file upload system:"
echo "   php test-upload.php"
echo ""
echo "📝 STEP 3: Test admin product image upload:"
echo "   Visit: https://techbuy-webapp-agbgf2gbgud8apaw.centralindia-01.azurewebsites.net/admin/products/create"
echo ""
echo "🎯 KEY FIXES INCLUDED:"
echo "✅ Persistent storage in /home/LogFiles/storage (survives container restarts)"
echo "✅ nginx configuration to serve uploaded files"
echo "✅ Filesystem disk pointing to persistent location"
echo "✅ Automatic directory creation and permissions"
echo "✅ Storage symlink for Laravel compatibility"
echo "✅ Test script for upload verification"
echo ""
echo "📊 AZURE ENVIRONMENT VARIABLES TO ADD (if needed):"
echo "   AZURE_STORAGE_PATH=/home/LogFiles/storage"
echo "   WEBSITES_ENABLE_APP_SERVICE_STORAGE=true"
echo ""
echo "❓ TROUBLESHOOTING:"
echo "   If uploads still fail, check:"
echo "   1. Run: ls -la /home/LogFiles/storage"
echo "   2. Check permissions: chmod -R 755 /home/LogFiles/storage"
echo "   3. Verify symlink: ls -la /home/site/wwwroot/public/storage"
echo "   4. Test manually: php test-upload.php"
