# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Laravel app to Azure Web App - techbuy-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, intl, pdo_pgsql, curl

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader --prefer-dist --no-progress

      - name: Set Laravel storage & cache permissions
        run: chmod -R 775 storage bootstrap/cache

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install NPM packages and build assets
        run: |
          npm install
          npm run build

      - name: Run Laravel optimizations (no .env needed, vars come from Azure)
        run: |
          php artisan config:clear || true
          php artisan route:clear || true
          php artisan view:clear || true
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: laravel-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read  # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: laravel-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F6C873D5C2034A84BC433F7568F73AFA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_175E4E055C434C79B8DDC1982C8FA4A9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D5DF7C74F9484387B0ED5831DAE33362 }}

      - name: Wait before deploy (avoid SCM restart conflicts)
        run: sleep 20

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'techbuy-webapp'
          slot-name: 'Production'
          package: .
          clean: true
