# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Laravel app to Azure Web App - techbuy-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, intl, pdo_pgsql, curl, mongodb
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader --prefer-dist --no-progress

      - name: Set Laravel permissions
        run: chmod -R 775 storage bootstrap/cache

      - name: Generate APP_KEY if missing
        run: |
          if ! grep -q "APP_KEY=" .env; then
            php artisan key:generate
          fi

      - name: Run Laravel optimizations
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install NPM packages and build assets
        run: |
          npm ci
          npm run build

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: laravel-app
          path: |
            .
            !node_modules/
            !tests/
            !.git/
            !.github/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: laravel-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Wait before deploy (avoid SCM conflicts)
        run: sleep 15

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'techbuy-webapp'
          slot-name: 'production'
          package: .
